### ISSUE TITLE
Sometimes placing an order that use PayPal payment method result in SDK timeout

### ISSUE THREAD

**Issue by citlacom** [commercelayer/commercelayer-sdk#14]
Hi @pviti - We are experiencing many SDK timeout requests when placing an order (transition to placed state) that use a PayPal payment source. Looks like behind the scenes CL backend is doing some operations that are time consuming and the SDK that tolerate a max timeout of 3 seconds determined that it took so much time and aborts the request. This is the error we see:

![Screenshot 2022-01-06 at 16 19 00](https://user-images.githubusercontent.com/802425/148406234-e7b87f09-b2e9-4078-ba9e-7fb5483a150f.png)

However, besides this error, it looks that the order transition correctly to "placed" state and completes the PayPal payment processing because the order state looks like this:

![Screenshot 2022-01-06 at 16 16 44](https://user-images.githubusercontent.com/802425/148406420-cfdcefc3-efd6-4da8-936b-0b272077ede3.png)

Is there a way to extend the SDK timeout? Can you help us to debug and determine why the "place" operation is taking 3 seconds sometimes and other times completing without exceeding the timeout?

The order ID of this test is: NbQLhleWOz

Thanks for your support!

**Comment by pviti** [comment]
``Hi @citlacom it is possible to change the SDK timeout setting it at a client level so that it will affect all subsequent requests or for a single API request

In the first case you can define it when you create the client instance:
`
const cl = commercelayer({
	organization: 'your-organization-slug',
	accessToken: 'a-valid-access-token',
	timeout: 5000,
})
`
or later:
`
cl.config({ timeout: 5000 })
`

If instead you want to define the timeout for a single request you have to specify it in the options parameter, for example:
`
const customers = await cl.customers.list({
    pageSize: 2, 
    pageNumber: 2, 
    sort: { created_at: 'desc', updated_at: 'asc' }, 
    fields: ['email'] }, 
    { timeout: 5000 }
)
`
